### ISSUE TITLE
add theme and Plugins

### ISSUE THREAD

**Issue by Happyfeet01** [guessi/docker-yourls#1]
Hi, 

How can i add custom themes and Plugins? 

Is this in conf/opt/yourls/ 

Currently i have only an white Page.  The Admin Backend works.

**Comment by guessi** [comment]
@Happyfeet01 I would recommend you the have a look at the [theme](https://github.com/YOURLS/awesome-yourls#themes) section under the [awesome-yourls](https://github.com/YOURLS/awesome-yourls#themes) project to find the theme that most suitable for you.

Further, I just made a sample Dockerfile for you as example that you may find it [here](https://github.com/guessi/docker-yourls/blob/master/dockerfiles/Dockerfile.theme).

Please let me know if there's anything unclear.

![image](https://user-images.githubusercontent.com/984415/146199957-9bdaa7c4-6738-40dd-8254-2d12dba3d880.png)

**Comment by giulio-perosino** [comment]
I'm having the same problem when activating the plugin. I think the problem is the location of the frontend folder that is extracted in the wrong directory (not the root of the yourls installation).

https://github.com/guessi/docker-yourls/blob/b0a8c68229e602a0bf0b1a53fdb0179a6cef4c72/Dockerfile#L107

**Comment by guessi** [comment]
@giulio-perosino thanks for feedback, I will check later once I back to my laptop.

**Comment by guessi** [comment]
Hi,

I just checked with current latest `guessi/docker-yourls:1.9.2-theme` but I'm not able to reproduce the issue on my side.

Could you please confirm you are working with `guessi/docker-yourls:1.9.2-theme` ?

- https://github.com/guessi/docker-yourls/blob/master/docker-compose.yaml#L27-L28

<img width="1674" alt="image" src="https://github.com/guessi/docker-yourls/assets/984415/511afb07-b91f-43b5-a39f-de9be7c970be">

**Comment by guessi** [comment]
Also tried to switch Dark/Light Mode, it looks good to me.

### Dark Mode
<img width="557" alt="image" src="https://github.com/guessi/docker-yourls/assets/984415/1ce0b427-102c-49c4-beca-942b23fd0ebf">

### Light Mode
<img width="539" alt="image" src="https://github.com/guessi/docker-yourls/assets/984415/e9262a94-75ca-4659-91cf-f1fb10ef423e">

**Comment by rursache** [comment]
https://github.com/guessi/docker-yourls/pull/12 provides details on this

**Comment by guessi** [comment]
Thanks... now I know what the "White/blank page" is talking about 😆

**Comment by guessi** [comment]
Thanks... now I know what the "White/blank page" is talking about.

I believe all details have been mentioned at upstream documentation
- https://yourls.org/docs/guide/advanced/public-shortening

and the discussion here
- https://github.com/orgs/YOURLS/discussions/3638#discussioncomment-7192119

I also updated the FAQ section to address this common question
- https://github.com/guessi/docker-yourls#faq
