### ISSUE TITLE
Move to official image builds?

### ISSUE THREAD

**Issue by guessi** [guessi/docker-yourls#10]
### Brief history of the repositories

Back in 2017, I was a user of YOURLS (_Great thanks to upstream maintainers_). I found it's hard to build YOURLS into container image so I publish my customized YOURLS image build and scripts on [May 7, 2017](https://github.com/guessi/docker-yourls/commit/de4781444ee64edb12abaa3af401b383208817e4). Around half year later, [upstream YOURLS maintainers](https://github.com/YOURLS/YOURLS/graphs/contributors) published an official repo called "[YOURLS/docker](https://github.com/YOURLS/docker)" to build container images for YOURLS project on [Nov 11, 2017](https://github.com/YOURLS/docker/commit/75e37b0cabe62ba4d4691c2d0eb883f4a811c727). So it became two different image repositories.

### Description

As two images build process approaches are very different, should we adopt change for these changes? or maybe I should encourage people to use Official Image builds? - https://github.com/YOURLS/docker

**Comment by ARezaK** [comment]
probably should encourage ppl to use official build?

**Comment by guessi** [comment]
@ARezaK sorry for the late reply... yes, I should add a banner/notification for users, let me create a PR here.
