### ISSUE TITLE
Multiple User Support

### ISSUE THREAD

**Issue by Lord0fBytes** [guessi/docker-yourls#11]
Is there an ability to use this with multiple users? I'd like to have 3-4 usernames and passwords for this.

**Comment by guessi** [comment]
@Lord0fBytes I think it is depends on upstream how YOURLS communicity implement its logic.

The magic behind the scene could be found at the code block below,
* https://github.com/guessi/docker-yourls/blob/1.9.2-3/conf/opt/yourls/user/config.php#L62-L69
* https://github.com/guessi/docker-yourls/blob/1.9.2-3/env.yourls#L31-L35

As you may see, it's done by replacing the env variables, not that easy to maintain with script replacement.

I would suggest you to turn to [YOURLS/YOURLS](https://github.com/YOURLS/YOURLS/issues) for feature request, here's the FR link for you,

* https://github.com/YOURLS/YOURLS/issues/1255

**Comment by guessi** [comment]
Additional [comments](https://github.com/guessi/docker-yourls/commit/c811defc8886f4ed1d9f73009a93bfe136ae4daa) added to `Dockerfile` and `env.yourls`.
