### ISSUE TITLE
Can't login...

### ISSUE THREAD

**Issue by stevenmcastano** [guessi/docker-yourls#13]
No matter what username and password I enter, it doesn't work...

I have an old install running under nginx/php-fpm, and I'm trying to deploy this docker container to connect to that other DB... the debug into shows that I'm connected, but after entering the admin username and password, I just get kicked back to the login screen again and told it's an invalid username or password...

Any ideas what to try next??

**Comment by guessi** [comment]
@stevenmcastano it's aim to provide quick start experience for new users, as for migrating from existed ones, you would need to go through backup restore process, or manually edit env files before you do "docker compose up". Check README.md for more details.

**Comment by stevenmcastano** [comment]
I did modify the env file, it does appear to be connecting to the database... when I turn on debug messages it shows me on the login screen that it is connect to my remote database, but no matter I do, I can't get it to let me log in.

**Comment by guessi** [comment]
@stevenmcastano 

As you mentioned you are using existed database, I would assume you are not using the one created by `docker-compose.yaml`, definition [HERE](https://github.com/guessi/docker-yourls/blob/master/docker-compose.yaml#L33-L34). If you are going to use existed database, you would need to change the line [HERE](https://github.com/guessi/docker-yourls/blob/master/env.yourls#L22-L23) to make it possible to connected to external one. Could you please check on that? check the message below for detailed explanation.

### Explanation

The setup below created link between `yourls` and `mysql (the container, created by compose)`, at the same time, it would create an alias for that, called `mysql (the domain name)` 
https://github.com/guessi/docker-yourls/blob/695c0224d9d1fcca4020d062c59d9b7ae7a8aca1/docker-compose.yaml#L33-L34

Then, the `env.yours` defines where the database for `yourls` is
https://github.com/guessi/docker-yourls/blob/695c0224d9d1fcca4020d062c59d9b7ae7a8aca1/env.yourls#L22-L23

And replace the actual variable at `config.php`
https://github.com/guessi/docker-yourls/blob/695c0224d9d1fcca4020d062c59d9b7ae7a8aca1/conf/opt/yourls/user/config.php#L23-L25

### Additional notes

As the env files are in `ini` format, it would have some limitations, please be aware of that.
> Space ` `, equal sign `=` and number sign `#` are not allowed
* https://github.com/guessi/docker-yourls/?tab=readme-ov-file#limitations-for-environment-files

If it still not resolving your issue, please describe more about how you turn on the debug mode? and what message did you got? and from database side of view, is there any new connection established after compose up?

I hope that help.

**Comment by guessi** [comment]
No response after month, closing...
