### ISSUE TITLE
(Question) (startup) Port 80 already in use

### ISSUE THREAD

**Issue by retrobunny** [guessi/docker-yourls#4]
Hi! I have a question about getting started. (New to docker / YOURLS)

When I run `docker-compose up` I get the error that port 80 is in use.

![Screen Shot 2022-04-02 at 3 40 19 PM](https://user-images.githubusercontent.com/12666226/161403707-2ba2a3ba-fc1e-4d5c-938b-7db1bc6b4d7f.png)

If I switch any references of port 80 -> 81, the error goes away, but i'm unable to navigate to `http://localhost/admin/index.php` or see anything on `localhost` or `localhost:80`

Is there anything else I should try? Also if I want to see the YOURLS source code that is being pulled in how would I do that? 

Appreciate the help, and Thanks!

**Comment by guessi** [comment]
@Agupta00 it generally means your `80` port have been occupied by another application/service.

I recommend you to try `docker ps` first to find if there's any other container running with port `80`.

Then, try the follow commands according to the operation system you are running with,
- For `macos` host, please run `lsof -i 4 -a | grep LISTEN` or `netstat -ntl`.
- For `Linux` host, please run `netstat -ntlp`.

I believe that you could find a process using port `80` before you run `docker-yourls`.

**Comment by retrobunny** [comment]
Hm, when I same thing at home instead of at the coffee shop it worked! Thanks for the response.
