### ISSUE TITLE
Update to 1.9...?

### ISSUE THREAD

**Issue by stratosgear** [guessi/docker-yourls#5]
Hi,

Not a real issue (depends on how you see these things), but could you update the image to [1.9](https://github.com/YOURLS/YOURLS/releases)...?

My installation starts popping an upgrade reminder.

Thanks!!!

**Comment by guessi** [comment]
@stratosgear thanks for notifying me, will upgrade the package later these days.

**Comment by guessi** [comment]
**_Release Notes:_**
- https://github.com/YOURLS/YOURLS/releases/tag/1.9
- https://blog.yourls.org/2022/04/yourls-1-9-nergal-released/

**_Change Log:_**
- https://github.com/YOURLS/YOURLS/blob/master/CHANGELOG.md

**_Documentation:_**
- https://docs.yourls.org/

**_Docker Image released by upstream YOURLS:_**
- https://github.com/YOURLS/docker
