### ISSUE TITLE
Should this not be 1.9.1?

### ISSUE THREAD

**Issue by deon-vector** [guessi/docker-yourls#7]
https://github.com/guessi/docker-yourls/blob/b9db42f0ebdb7b9806c4952a8a959e1bdbf6a606/dockerfiles/Dockerfile#L14
I used your docker-compose.yml file to bring up yourls but when I'm in the admin area it says I'm running 1.9 and I should upgrade to 1.9.1

I'm wondering if your main Dockerfile should be pointing to 1.9.1 and not 1.9

**Comment by guessi** [comment]
@vector-drodden nice catch 👍 I'm going to fix it now, thanks for reporting.

**Comment by guessi** [comment]
Just fixed it locally, and I'm going to do few tests and publish a new image soon.

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/984415/217578606-ec3fa4e9-0c13-4cf5-a1a5-a23dbf6bc4e2.png">
