### ISSUE TITLE
Build container images with GitHub Actions

### ISSUE THREAD

**Issue by guessi** [guessi/docker-yourls#9]
### Description

It's been a long time having no automation build but all image built manually after Docker Hub stop offering build for Free accounts, need to find a way to get image build weekly or monthly to ensure we could get security fixes such as Debian, PHP, Apache, etc.

**Comment by rursache** [comment]
all you need to do for this is to create a new action, pick the "build and deploy docker image to github repository" template and then edit the crontab inside. shouldn't take more than 5 minutes

i made a repo to build yours and publish the images to mine: https://github.com/rursache/YOURLS-Docker-Image

**Comment by guessi** [comment]
@rursache Actually I'm aware it's a simple "minutes" job.... it's just a lazy man put a note but forgot there's a note 😂

But now, I have no reason to be lazy 😣 your sample GHA scripts looks awesome to me, I should adopt it immediately.

**Comment by guessi** [comment]
It's now build with GHA - 1b462ee4dc37c90eabcfd0c4cbac1df477b7477d

- https://github.com/guessi/docker-yourls/actions/runs/7358876432

Closing
